version: "3.9"
services:
  reverse-proxy:
    image: nginx:${NGINX_IMAGE_TAG}
    depends_on:
      - virtuoso
    volumes:
      - ${PWD}/nginx:/etc/nginx/templates
      - ${PWD}/nginx/ssl-proof:/var/www/html/ssl-proof
      - letsencrypt:/etc/letsencrypt
    environment:
      SERVER_NAME: ${SERVER_NAME}
      PORT_NGINX: ${PORT_NGINX}
      PORT_NGINX_SSL: ${PORT_NGINX_SSL}
      PORT_VIRTUOSO: ${PORT_VIRTUOSO_HTTP}
    ports:
      - ${PORT_NGINX}:${PORT_NGINX}
      - ${PORT_NGINX_SSL}:${PORT_NGINX_SSL}

  certbot:
    image: certbot/certbot:${CERTBOT_IMAGE_TAG}
    volumes:
      - ${PWD}/nginx/ssl-proof:/var/www/html/ssl-proof
      - letsencrypt:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c \
      "trap exit TERM; while :; do certbot ${CERTBOT_RENEW_COMMAND} ; sleep 7d & wait $${!}; done;"

  virtuoso:
    image: openlink/virtuoso-opensource-7:${VIRTUOSO_IMAGE_TAG}
    container_name: virtuoso_container
    volumes:
      - ${PWD}/data:${MOUNT_DIR}:ro
      - ${PWD}/.virtuoso:/database
    environment:
      DBA_PASSWORD: ${PASSWORD_VIRTUOSO}
      # cf. http://docs.openlinksw.com/virtuoso/dbadm/#sampleinifile
      VIRT_HTTPServer_ServerPort: ${PORT_VIRTUOSO_HTTP}
      VIRT_Parameters_ServerPort: ${PORT_VIRTUOSO_ISQL}
      VIRT_Parameters_QueryLog: /database/virtuoso.qrl
      VIRT_Parameters_DirsAllowed: ${Parameters_DirsAllowed}
      VIRT_Parameters_NumberOfBuffers: ${Parameters_NumberOfBuffers}
      VIRT_Parameters_MaxDirtyBuffers: ${Parameters_MaxDirtyBuffers}
    ports:
      - ${PORT_VIRTUOSO_ISQL}:${PORT_VIRTUOSO_ISQL} # isql (interactive SQL)
      - ${PORT_VIRTUOSO_HTTP}:${PORT_VIRTUOSO_HTTP} # http

volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/nginx/letsencrypt
      o: bind